name: PropelORM CI

on: [
    push,
    pull_request
]

jobs:
    testsuite:
        runs-on: ubuntu-18.04
        strategy:
            fail-fast: false
            matrix:
                php-version: ['7.2', '7.4', '8.0']
                db-type: [sqlite, mysql, pgsql, agnostic]
                postgres-version: ['9.5', '9.6', '10', '11', '12']
                mariadb-version: ['10.1', '10.2', '10.3', '10.4']
                symfony-version: ['3-min', '3-max', '4-min', '4-max', '5-min', '5-max']

        steps:
            - name: print-info
              run: |
                  echo "PHP Version: ${{ matrix.php-version }}"
                  echo "DB Type: ${{ matrix.db-type }}"
                  echo "PostresSQL Version: ${{ matrix.postgres-version }}"
                  echo "MariaDB Version: ${{ matrix.mariadb-version }}"
                  echo "Symfony Version: ${{ matrix.symfony-version }}"


    code-style-and-static-analysis:
        runs-on: ubuntu-18.04
        strategy:
            fail-fast: false
            matrix:
                php-version: ['7.4']

        steps:
            - uses: actions/checkout@v1
              with:
                  fetch-depth: 1

            - name: Composer get cache directory
              id: composer-cache
              run: |
                  echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Composer cache
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-

            - name: Composer validate
              run: composer validate

            - name: Composer install
              run: composer install --prefer-dist --no-interaction

            - name: Code Style
              run: composer cs-check

            - name: PHPStan
              run: composer stan

            - name: Psalm
              run: composer psalm
