name: Propel Test Suite

on: [push, pull_request]

jobs:
    testsuite:
        runs-on: ubuntu-18.04
        strategy:
            fail-fast: false
            matrix:
                php-version: ['7.2', '7.4']
                db-type: [sqlite, mysql, pgsql, agnostic]
                symfony-version: [ '3-min', '3-max', '4-min', '4-max', '5-min', '5-max' ]
        steps:
            - name: Install PostgreSQL latest
              if: matrix.db-type == 'pgsql' && matrix.php-version == '7.4'
              uses: CasperWA/postgresql-action@v1.2
              with:
                  postgresql db: 'propel-tests'
                  postgresql user: 'postgres'
                  postgresql password: 'postgres'

            - name: Install PostgreSQL min
              if: matrix.db-type == 'pgsql' && matrix.php-version == '7.2'
              uses: CasperWA/postgresql-action@v1.2
              with:
                  postgresql version: 9
                  postgresql db: 'propel-tests'
                  postgresql user: 'postgres'
                  postgresql password: 'postgres'

            - name: Install MariaDb latest
              if: matrix.db-type == 'mysql' && matrix.php-version == '7.4'
              uses: getong/mariadb-action@v1.1

            - name: Install MariaDb min
              if: matrix.db-type == 'mysql' && matrix.php-version == '7.2'
              uses: getong/mariadb-action@v1.1
              with:
                  mariadb version: '10.2'

            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup PHP, with composer and extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: json, libxml, pdo, pdo_mysql, pdo_sqlite, pdo_pgsql, sqlite3
                  coverage: none
            - name: Get composer cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            - name: Cache composer dependencies
              uses: actions/cache@v1
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: ${{ runner.os }}-composer-
            - name: Move specific composer.json (Symfony version ${{ matrix.symfony-version }})
              run: mv tests/composer/composer-symfony${{ matrix.symfony-version }}.json composer.json
            - name: Install dependencies (Symfony version ${{ matrix.symfony-version }})
              run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
            - name: Setup Postgresql dabase for test suite
              if: matrix.db-type == 'pgsql'
              run: tests/bin/setup.pgsql.sh
              env:
                  PGPASSWORD: 'postgres'
                  DB_NAME: 'propel-tests'
                  DB_USER: 'postgres'
                  DB_PW: 'postgres'
            - name: Setup the dabase for test suite
              if: matrix.db-type != 'agnostic' && matrix.db-type != 'pgsql'
              run: tests/bin/setup.${{ matrix.db-type }}.sh
            - name: Run Postgresql tests
              if: matrix.db-type == 'pgsql'
              run: tests/bin/phpunit.pgsql.sh
              env:
                  DB_NAME: 'propel-tests'
                  DB_USER: 'postgres'
                  DB_PW: 'postgres'
            - name: Run tests
              if: matrix.db-type != 'pgsql'
              run: tests/bin/phpunit.${{ matrix.db-type }}.sh
